### ISSUE TITLE
`SetRecordDirectoryAsync` throws `FailureResponseException` "UnknownRequestType: Your request type is not valid."

### ISSUE THREAD

**Issue by Jvs34** [jeiea/ObsStrawket#2]
OBS version: `29.1.3`
Library version: `0.14.0`
OBS Websocket version: `5.2.3` RPC Version `1`
Log: [2023-09-11 16-38-55.txt](https://github.com/jeiea/ObsStrawket/files/12577749/2023-09-11.16-38-55.txt)
Repro project: [ObsRepro.zip](https://github.com/jeiea/ObsStrawket/files/12577797/ObsRepro.zip)

I can't use ObsClientSocket.SetRecordDirectoryAsync to set the OBS recording folder, it throws a FailureResponseException  as if the command was not recognized.

**Comment by Jvs34** [comment]
Oh, this seems to have been an [oversight](https://github.com/obsproject/obs-websocket/commit/ac00465565439e6d8a7dae259ce36a5c790c2ac8) by the obs-websocket maintainers, this was fixed in 5.3.0 but the mainline OBS is currently using 5.2.3.

The recommended workaround is to use [SetProfileParameter](https://github.com/obsproject/obs-websocket/issues/1142#issuecomment-1677281690) for now.

Now that I look closely, the method's comment does have info about the version it works in, but I was expecting it to work by default considering I have everything up to date and all, or at the very least a different exception.

**Comment by jeiea** [comment]
See [0.13.0 changelog](https://github.com/jeiea/ObsStrawket/blob/main/CHANGELOG.md#0130).

Do you want me to add something like `NotSupportedException`?

**Comment by Jvs34** [comment]
> See [0.13.0 changelog](https://github.com/jeiea/ObsStrawket/blob/main/CHANGELOG.md#0130). Are there any changes you'd like to see in this library?

I'd like to see a popup of the release notes when you install/update the library, I had no idea there was one as it wasn't anywhere in the nuget.org page or the readme.
Other than that, not really, I'm still moving over from the old obs-websocket nuget and I haven't fully tested this one.

I suppose the issue remains until 5.3.0 releases to the main OBS, but this can be closed.

**Comment by jeiea** [comment]
I admit changelog is not enough and someone ever notice that we can't use this method neither.

It would be nice if I can describe that method is experimental more prominently but there's no proper feature in doc comments.

Currently I'm considering providing workaround implementation (though I'm not sure this is right) with the old obs websocket.

**Comment by djinnet** [comment]
What is the current status on this? 

I saw someone on claimed that it got fixed [Link to the websocket setrecorddirectory doc](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#setrecorddirectory)
[Link to the pull request from obs-websocket-dotnet](https://github.com/BarRaider/obs-websocket-dotnet/pull/135)

They mentioned that 5.3.0 is released to the main OBS in [OBS30 ](https://github.com/obsproject/obs-studio/releases/tag/30.0.2)

**Comment by jeiea** [comment]
I didn't amend implementation, so if an user use OBS 30 or above `SetRecordDirectoryAsync` will work.

Do you think this issue should be closed?

**Comment by Jvs34** [comment]
> Do you think this issue should be closed?

Yes, I just tested my own Repro project after updating obs and the method works just fine.
